apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Set according to your requirements
  storageClassName: mysql-storage # Name of your storage class
  hostPath:
    path: /var/www/storage/mysql # Path on your dedicated server

