apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Set according to your requirements
  storageClassName: mongodb-storage # Name of your storage class
  hostPath:
    path: /var/www/storage/mongodb # Path on your dedicated server

